[package]
name = "libaaudio-sys"
version = "0.1.0"
authors = ["Julian Aichholz <julianaichholz@gmail.com>"]
edition = "2018"
links = "aaudio"
build = "build.rs"

[build-dependencies]
bindgen = "0.52.0" # bindgen = "0.49.2"

[lib]
name = "aaudio"
